version: '3.9'
services:
  app:
    container_name: movasite
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=false