# Generated by Django 4.0.3 on 2022-04-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesiton',
            new_name='question',
        ),
    ]
