# Generated by Django 4.0.3 on 2022-04-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_tests', '0002_rename_quesiton_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='question_number',
            new_name='max_questions',
        ),
    ]
