# Generated by Django 4.0.3 on 2022-04-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_tests', '0003_rename_question_number_language_max_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
