# Generated by Django 4.0.3 on 2022-04-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_tests', '0004_alter_language_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='time',
            field=models.PositiveIntegerField(default=0, help_text='Тривалість тесту'),
            preserve_default=False,
        ),
    ]
