# Generated by Django 4.0.3 on 2022-04-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_tests', '0005_language_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', models.CharField(max_length=200)), ('Option2', models.CharField(max_length=200)), ('Option3', models.CharField(max_length=200)), ('Option4', models.CharField(max_length=200))], max_length=200),
        ),
    ]
