# Generated by Django 4.0.3 on 2022-04-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_tests', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200),
        ),
    ]
