# Generated by Django 4.0.3 on 2022-04-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_tests', '0007_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
    ]
